### ISSUE TITLE
Downloading Missing Albums instead of Monitored?

### ISSUE THREAD

**Issue by CHlLL7** [RandomNinjaAtk/lidarr-automated-downloader#1]
Hello, first of all, Great Script!
I noticed though that many already existing Albums in my Music Library are downloaded again. Does your script pull Info from Missing Albums or Monitored?

Many Thanks!

**Comment by abnersnell** [comment]
I second the great script comment!  Any advice on deezloader settings when it comes to download directories and artist folders -> then album folder -> then tracks. I am having permission issues once the files get moved by the script from deezer download directory to lidarr temp directory.

**Comment by RandomNinjaAtk** [comment]
@marcel5454 The script pulls from missing and cutoff album lists. So it's probably searching for albums that are still monitored that haven't reached cutoff. So it's working as intended. You'd need to adjust your cutoff profile settings.

@abnersnell The script is designed not to use any folders. So you should disable all folder options in app web interface. As for permissions issue, the config file has an option to set the permissions that you want.

https://github.com/RandomNinjaAtk/lidarr-automated-downloader/blob/c70c0dbc90ea4bcb144149126ae2b3c7bbc06a7c/config#L34

https://github.com/RandomNinjaAtk/lidarr-automated-downloader/blob/c70c0dbc90ea4bcb144149126ae2b3c7bbc06a7c/config#L35
