### ISSUE TITLE
Some filenames are missing their artist

### ISSUE THREAD

**Issue by ghost** [RandomNinjaAtk/lidarr-automated-downloader#10]
Using your docker image.

Some files are created without their artist in their filenames which results in Lidarr unable to import them from the lidarr-import directory. 

**The Rolling Stones - A Bigger Bang (2009 Re-Mastered) (2009) (ALBUM) (WEB)-DLCLIENT**

> 101 - Rough Justice.flac
> 102 - Let Me Down Slow (Remastered).flac
> 103 - It Won't Take Long (Remastered).flac
> 104 - Rain Fall Down.flac
> 105 - Streets Of Love.flac
> 106 - Back Of My Hand (Remastered).flac
> 107 - She Saw Me Coming (Remastered).flac
> 108 - Biggest Mistake (Remastered).flac
> 109 - This Place Is Empty (Remastered).flac
> 110 - Oh No, Not You Again (Remastered).flac
> 111 - Dangerous Beauty (Remastered).flac
> 112 - Laugh, I Nearly Died (Remastered).flac
> 113 - Sweet Neo Con (Remastered).flac
> 114 - Look What The Cat Dragged In (Remastered).flac
> 115 - Driving Too Fast (Remastered).flac
> 116 - Infamy (Remastered).flac

log:

> Deezer Matched Album Title: A Bigger Bang (2009 Re-Mastered) (ID: 384230)
> Album Link: https://www.deezer.com/album/384230
> Album Release Year: 2009
> Album Release Type: album
> Album Lyric Type: Clean
> Album Duration: 1:04:07s
> Album Track Count: 16
> Downloading 16 Tracks...
> Downloading collection
> Downloading: The Rolling Stones - Rain Fall Down
> Downloading: The Rolling Stones - Let Me Down Slow (Remastered)
> Downloading: The Rolling Stones - Rough Justice
> Downloading: The Rolling Stones - It Won't Take Long (Remastered)
> Done!
> Done!
> Done!
> Downloading: The Rolling Stones - Streets Of Love
> Downloading: The Rolling Stones - Back Of My Hand (Remastered)
> Downloading: The Rolling Stones - She Saw Me Coming (Remastered)
> Done!
> Downloading: The Rolling Stones - Biggest Mistake (Remastered)
> Done!
> Downloading: The Rolling Stones - This Place Is Empty (Remastered)
> Done!
> Downloading: The Rolling Stones - Oh No, Not You Again (Remastered)
> Done!
> Done!
> Downloading: The Rolling Stones - Dangerous Beauty (Remastered)
> Downloading: The Rolling Stones - Laugh, I Nearly Died (Remastered)
> /storage/downloads/lidarr/dlclient/ 112 - Laugh, I Nearly Died (Remastered)
> Done!
> Downloading: The Rolling Stones - Sweet Neo Con (Remastered)
> Done!
> Downloading: The Rolling Stones - Look What The Cat Dragged In (Remastered)
> Done!
> Downloading: The Rolling Stones - Driving Too Fast (Remastered)
> Done!
> Downloading: The Rolling Stones - Infamy (Remastered)
> Done!
> Done!
> Done!
> Done!
> All done!
> Downloaded Album: A Bigger Bang (2009 Re-Mastered) (Format: FLAC; Length: 1:04:07s)
> Verified Track: 101 - Rough Justice.flac
> Verified Track: 102 - Let Me Down Slow (Remastered).flac
> Verified Track: 103 - It Won't Take Long (Remastered).flac
> Verified Track: 104 - Rain Fall Down.flac
> Verified Track: 105 - Streets Of Love.flac
> Verified Track: 106 - Back Of My Hand (Remastered).flac
> Verified Track: 107 - She Saw Me Coming (Remastered).flac
> Verified Track: 108 - Biggest Mistake (Remastered).flac
> Verified Track: 109 - This Place Is Empty (Remastered).flac
> Verified Track: 110 - Oh No, Not You Again (Remastered).flac
> Verified Track: 111 - Dangerous Beauty (Remastered).flac
> Verified Track: 112 - Laugh, I Nearly Died (Remastered).flac
> Verified Track: 113 - Sweet Neo Con (Remastered).flac
> Verified Track: 114 - Look What The Cat Dragged In (Remastered).flac
> Verified Track: 115 - Driving Too Fast (Remastered).flac
> Verified Track: 116 - Infamy (Remastered).flac
> SUCCESS: Artwork Extracted for Downlaod
> Downloaded: 16 Tracks
> Downloaded: 1 Synced Lyrics
> Downloaded: 1 Album Cover
> REPLAYGAIN TAGGING DISABLED
> Setting folder permissions (777)
> Setting file permissions (666)
> Notified Lidarr to scan "/storage/downloads/lidarr/lidarr-import/The Rolling Stones - A Bigger Bang (2009 Re-Mastered) (2009) (ALBUM) (WEB)-DLCLIENT" for import
> 

deemix default.json

> {
>   "downloadLocation": "",
>   "tracknameTemplate": "%artist% - %title%",
>   "albumTracknameTemplate": "%tracknumber% - %title%",
>   "playlistTracknameTemplate": "%position% - %artist% - %title%",
>   "createPlaylistFolder": true,
>   "playlistNameTemplate": "%playlist%",
>   "createArtistFolder": false,
>   "artistNameTemplate": "%artist%",
>   "createAlbumFolder": true,
>   "albumNameTemplate": "%artist% - %album%",
>   "createCDFolder": true,
>   "createStructurePlaylist": false,
>   "createSingleFolder": false,
>   "padTracks": true,
>   "paddingSize": "0",
>   "illegalCharacterReplacer": "_",
>   "queueConcurrency": 3,
>   "maxBitrate": "3",
>   "fallbackBitrate": true,
>   "fallbackSearch": false,
>   "logErrors": true,
>   "logSearched": false,
>   "createM3U8File": false,
>   "syncedLyrics": false,
>   "embeddedArtworkSize": 800,
>   "localArtworkSize": 1400,
>   "saveArtwork": true,
>   "coverImageTemplate": "cover",
>   "saveArtworkArtist": false,
>   "artistImageTemplate": "folder",
>   "PNGcovers": false,
>   "jpegImageQuality": 80,
>   "dateFormat": "Y-M-D",
>   "removeAlbumVersion": false,
>   "featuredToTitle": "0",
>   "titleCasing": "nothing",
>   "artistCasing": "nothing",
>   "executeCommand": "",
>   "tags": {
>     "title": true,
>     "artist": true,
>     "album": true,
>     "cover": true,
>     "trackNumber": true,
>     "trackTotal": false,
>     "discNumber": true,
>     "discTotal": false,
>     "albumArtist": true,
>     "genre": true,
>     "year": true,
>     "date": true,
>     "explicit": false,
>     "isrc": true,
>     "length": true,
>     "barcode": true,
>     "bpm": true,
>     "replayGain": false,
>     "label": true,
>     "lyrics": false,
>     "copyright": false,
>     "composer": false,
>     "involvedPeople": false,
>     "savePlaylistAsCompilation": false,
>     "useNullSeparator": false,
>     "saveID3v1": true,
>     "multitagSeparator": "default"
>   }
> }

**Comment by RandomNinjaAtk** [comment]
?
