### ISSUE TITLE
Using the script with the deemix docker

### ISSUE THREAD

**Issue by theg00s3** [RandomNinjaAtk/lidarr-automated-downloader#11]
Is there a way to use this script with the [deemix docker](https://hub.docker.com/r/bocki/deemix)?

**Comment by RandomNinjaAtk** [comment]
If your using docker, you should just use the official docker: https://github.com/RandomNinjaAtk/docker-lidarr-lad

This uses CLI based deemix, so it will not be able to integrate easily using the web interface.
