### ISSUE TITLE
Script pausing after verifying tracks

### ISSUE THREAD

**Issue by Rob-T** [RandomNinjaAtk/lidarr-automated-downloader#12]
The script runs fine; finds the albums to download and does so. It then verifies the tracks downloaded, but pauses once it reaches the last track. To continue past this, I have to hit 'enter' and then the script will continue saying,

```
ERROR: No artwork failed extraction
Downloaded: 15 Tracks
Downloaded: 0 Synced Lyrics
Downloaded: 1 Album Cover
Fixing tags
```

The script then continues on without issue until it downloads and then verifies the next downloaded and again pausing after verifying the last track downloaded (and again needing an 'enter' to continue.

Is this a bug or by design?

**Comment by RandomNinjaAtk** [comment]
I've not seen that issue in my case.

What quality do you have it set at?
Are you using the official docker or using the script externally? 

If external, I would have to guess your missing a required package that is used for fixing tags. Which is likely the cause for the pause...

**Comment by Rob-T** [comment]
Quality is set to FLAC and using the script externally. Other than this, the script runs fine (thank you for sharing it!!). 

EDIT: I've gone through and made sure all the required packages are installed as listed on the README.md. When looking at the album added in Lidarr, the album artwork is there, so not exactly sure what the error is about. I looked at the script code that give that error, but I don't really understand unfortunately.

**Comment by RandomNinjaAtk** [comment]
Hmm, I don't see any of that behavior using the docker container. The script appears to be pausing while attempting to fix the tags maybe?

https://github.com/RandomNinjaAtk/lidarr-automated-downloader/blob/4ab63be1ab33314be430f662d25dc3dd589912c6/lidarr-automated-downloader.bash#L856
And in that fixing tags code following that line... For flac it requires the use of metaflac, usually included in the "flac" package and for MP3 it requires eyeD3

If you have a chance, you can always try the docker container, I do all of my development and testing on the docker container.

**Comment by Rob-T** [comment]
I'm sorry, I have done a poor job at explaining where the issue happens....

The script runs, finds the albums from Lidarr marked as wanted and searches for them. It then downloads them from Deemix without issue. 

```
INFO:deemix:[Artist XXX - Track] Applying tags to the track
INFO:deemix:[Artist XXX - Track] Track download completed
INFO:deemix:[album_12345] Finished downloading.
All done!
Downloaded Album: Album ZZZ (Format: FLAC; Length: 57:49s)
```

After downloading, it verifies each track....

```
Verified Track: 01 - A.flac
Verified Track: 02 - B.flac
Verified Track: 03 - C.flac
Verified Track: 04 - D.flac
```

This is where it pauses. After completing the verification of each track, it will not proceed without pressing enter. Once I press enter, it will continue giving the following...

```
ERROR: No artwork failed extraction
Downloaded: 4 Tracks
Downloaded: 0 Synced Lyrics
Downloaded: 1 Album Cover

Fixing tags
01 - A.flac fixed...
02 - B.flac fixed...
03 - C.flac fixed...
04 - D.flac fixed...
```

It fixes the tags on each track without issue and continues on only pausing again once it has completed the 'verifying each track' stage on the next album.

**Comment by RandomNinjaAtk** [comment]
I made a small change, if you pull down the latest script files. Maybe see if that helps. The Artwork Extraction process requires ffmpeg.

https://github.com/RandomNinjaAtk/lidarr-automated-downloader/blob/e897f94dcca481e2bb8f14ae3b4892cbdb180709/lidarr-automated-downloader.bash#L999

One thing you could do, but you might not be. Is disable using all folders in Deemix (album/artist), you only want the audio files. It could be possible that because your client config is using folders, that it may be tripping it up. The docker does not use folders when downloading.

Also if you modify this line from: (Album Artwork function, use link above)
```
if ffmpeg -i "$file" -c:v copy "$downloaddir/folder.jpg" 2>/dev/null; then
```
To:
```
if ffmpeg -i "$file" -c:v copy "$downloaddir/folder.jpg"; then
```

You may be able to see the error. Also another reason could be, are you embedding the album art? If you have that disabled, since its extracting the embedded art, that may be the issue also.

Sorry, just lots of random thoughts...

**Comment by Rob-T** [comment]
OK, so downloaded your updated version but it still paused.  I changed the line you suggest to see the error and it's asking to overwrite folder.jpg (y/N)?

ffmpeg version 4.1.4-1~deb10u1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --prefix=/usr --extra-version='1~deb10u1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Input #0, flac, from '/home/user01/Downloads/music/01 - New Song.flac':
  Metadata:
    TITLE           : 123
    ARTIST          : AAA
    ALBUM           : BBB
    album_artist    : CCC
    track           : 1
    disc            : 1
    GENRE           : Rock
    DATE            : 1978-01-01
    LENGTH          : 253
    BPM             : 133.23
    PUBLISHER       : SSS
    ISRC            : XXX
    BARCODE         : 1111111
  Duration: 00:04:13.00, start: 0.000000, bitrate: 897 kb/s
    Stream #0:0: Audio: flac, 44100 Hz, stereo, s16
    Stream #0:1: Video: mjpeg, yuvj444p(pc, bt470bg/unknown/unknown), 800x800 [SAR 72:72 DAR 1:1], 90k tbr, 90k tbn, 90k tbc
    Metadata:
      comment         : Cover (front)
File '/home/user01/Downloads/music/folder.jpg' already exists. Overwrite ? [y/N]

**Comment by RandomNinjaAtk** [comment]
@Rob-T 

This change should fix it:
https://github.com/RandomNinjaAtk/lidarr-automated-downloader/commit/a5fe99792ee0be8924847ffd71413d3583576a41

Pull the latest and try again...

The docker image, doesn't have the client dl the artwork, it just pulls it out of the file. In your case, your deemix is also downloading the artwork and storing it in the folder. Thats why the error happens. But I included 2 changes that should fix that...

The new change, will skip it if found already and last resort, it will overwrite the file, so you should never see the pause/error again...

**Comment by Rob-T** [comment]
Fixed! Again, thanks for the great work here!

Cheers.
