### ISSUE TITLE
Keep getting Download error messages in the log

### ISSUE THREAD

**Issue by m00nwtchr** [RandomNinjaAtk/lidarr-automated-downloader#14]
It looks like its finding the songs correctly, but then fails to download, is there any way to enable log output from deemix to see what's going on?

**Comment by RandomNinjaAtk** [comment]
@lmarianski I know you closed this, but if you follow these instructions, you can see log output 


https://github.com/RandomNinjaAtk/docker-lidarr-lad/issues/36#issuecomment-653782548

**Comment by m00nwtchr** [comment]
Ah thx, turns out i just missed the part where you have to add a deezer token.
