### ISSUE TITLE
can you implement tidal-dl (cli) as a downloader

### ISSUE THREAD

**Issue by zobe123** [RandomNinjaAtk/lidarr-automated-downloader#15]
would be nice if you can implement this :-)  tidal-dl (cli) [https://yaronzz.top/post/tidal_dl_installation/#Install]

**Comment by RandomNinjaAtk** [comment]
I could possibly see that as being possible. But it could end up being much more limited. I'll look into it.

**Comment by zobe123** [comment]
Thx, just let me know if any test required

**Comment by RandomNinjaAtk** [comment]
So some basic investigation. It looks to be usable, but it would likely only work using archive mode. And it would require some manual setup possibly. Cannot likely fully automate account login. Would you still be interested even with the limitations? It may also be possible to use it for music videos from the looks but that would highly be dependent on musicbrainz having the videos individually linked. This would also require musicbrainz to have the artist tidal links added for archive functionality.

**Comment by RandomNinjaAtk** [comment]
Second thought, I'm not sure it would be usable. The app may require some modifications to enable it to work

**Comment by spoonys** [comment]
That’s a shame. I just discovered this project and though if I could link with tidal-dl I would be a happy man!

**Comment by RandomNinjaAtk** [comment]
From my brief testing experience, deemix is the better client, and the other one would be much more limited, archive only mode. So it does not make sense to make a change at all at this time.
