### ISSUE TITLE
UrlBase

### ISSUE THREAD

**Issue by lokiberra** [RandomNinjaAtk/lidarr-automated-downloader#2]
If a UrlBase is set up in Lidarr, LAD cannot communicate with it (when using the default config in the Docker Image) as the API needs that in the URL

ie. ${LidarrApiKey} gives only http://127.0.0.1:8686 in:

`curl -s --header "X-Api-Key:"${LidarrApiKey} --request GET  "$LidarrUrl/api/v1/wanted/missing/?page=1&pagesize=${amount}&includeArtist=true&monitored=true&sortDir=desc&sortKey=releaseDate" -o temp-lidarr-missing.json
	curl -s --header "X-Api-Key:"${LidarrApiKey} --request GET  "$LidarrUrl/api/v1/wanted/cutoff/?page=1&pagesize=${amount}&includeArtist=true&monitored=true&sortDir=desc&sortKey=releaseDate" -o temp-lidarr-cutoff.json`

needs to be http://127.0.0.1:8686/urlbase if one is configured

**Comment by RandomNinjaAtk** [comment]
I'm not sure how to account for that at the moment. I don't use a urlbase, so I've never seen this issue. I use a subdomain for reverse proxy, which avoids the need for using urlbase.

Edit, if you were not using my docker image, you could easily set it that way in the config file.

**Comment by lokiberra** [comment]
I also use a subdomain for reverse proxy, I'm not sure why I had the url base configured.... But some people might actually use that option. I think it could be an option in the config file and an environmental variable for the docker container. If someone doesn't have one it would just be blank. I have not tested this yet.

**Comment by RandomNinjaAtk** [comment]
I'd have to think about the implementation, but that only applies to the docker, not this script here. So I"m going to close this..

**Comment by RandomNinjaAtk** [comment]
FYI this was recently resolved in the docker
