### ISSUE TITLE
Parse error: Invalid numeric literal

### ISSUE THREAD

**Issue by Norin-Radd** [RandomNinjaAtk/lidarr-automated-downloader#3]
Hi,

I have this setup on ubuntu server and not on docker, just a reminder.
It gives me an parse error: Invalid numeric literal when downloading 
Artist: Gina X Performance 
Album: X-traordinaire.
here is a pic of error
![gina x performance X-traordinaire issue](https://user-images.githubusercontent.com/14083654/78063045-7ccfe500-7387-11ea-85d7-1a36b613cfa4.png)

**Comment by RandomNinjaAtk** [comment]
So, after looking into this, I cannot replicate the issue. This is not a bug with the script, but an issue with the software dependencies and versions you have installed. (16.04 packages vs 18.04) I'd recommend updating to newer OS/packages to resolve this.
