### ISSUE TITLE
add spotify downlaod ?

### ISSUE THREAD

**Issue by Nonobis** [RandomNinjaAtk/lidarr-automated-downloader#4]
Hello, 

I love your automated download, i use it with a docker package on my unraid. It's perfect. My wifie love music and since i have your script ..... she is happy !

I don't known if it's possible .. but could try to download also with spotify ?
There is not all album on deezer for every artist, maybe with spotify ?

Thanks :)

**Comment by t3rminalx** [comment]
Have you tried spotdl?

https://github.com/ritiek/spotify-downloader

**Comment by RandomNinjaAtk** [comment]
I think it's kind of out-of-scope for this.... but if there was a similar client that could be used in a similar way, I could consider it. But I'm not really aware of any....

**Comment by Nonobis** [comment]
cool, only if possible and you have time :)
