### ISSUE TITLE
Download stuck with duplicate songs in same album

### ISSUE THREAD

**Issue by ghost** [RandomNinjaAtk/lidarr-automated-downloader#7]
When album has multiple song with the same name, download script gets stuck with checking if download has started.
This happens because deezloader will not re-download the file that already exist, so nothing will ever be newer than "temp-track" file, so the while loop gets stuck
Example album: https://www.deezer.com/album/6803264

**Comment by RandomNinjaAtk** [comment]
Please use the latest code and d-fi, deezloader is no longer supported because of recent changes.
