### ISSUE TITLE
Not Found is too strict?

### ISSUE THREAD

**Issue by justinglock40** [RandomNinjaAtk/lidarr-automated-downloader#8]
So i'm going through the not found log and it is not finding stuff that is actually available is there anyway to reduce the strict search to pull more results? I'm using the docker version.

<img width="1180" alt="image" src="https://user-images.githubusercontent.com/23133649/79608605-4f8f7080-80c3-11ea-87e7-b13c150e5007.png">

<img width="1233" alt="image" src="https://user-images.githubusercontent.com/23133649/79608566-3edefa80-80c3-11ea-8a90-f058003cbfb3.png">

**Comment by RandomNinjaAtk** [comment]
So your issue there is it looks like your searching for a single, and there is no single in those results. Those are part of an album.

The matching is very dependent on album naming, and track count and this doesn't use an app at all to search. It's pulling info directly for an artist from the API and using that to match.

The way to improve matches, is to add releases that better match naming and track counts to musicbrainz.

Also on that note, if anyone can write a better matching engine then what is currently used, by all means, Pull requests are welcome.
